config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  resources :docs

  get 'welcome/index'

  root to: "welcome#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doc.rb
class Doc < ApplicationRecord
  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_many :docs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  before_action :set_doc, only: [:show, :edit, :delete, :update, :destroy]
  before_action :authenticate_user!
  
  def index
    @docs = current_user.docs
  end

  def show
  end

  def new
    if current_user
        @doc = current_user.docs.build
    else
      redirect_to new_user_session_path, notice: 'You have to login first!'
    end
  end

  def create
    @doc = current_user.docs.build(secure_params)
    if @doc.save
      redirect_to @doc, notice: "Document was successfully created!"
    else
      render new
    end
  end

  def delete
  end

  def destroy
  end

  def edit
  end

  def update
    if @doc.update(secure_params)
      redirect_to @doc, notice: "Document was successfully updated"
    else
      render edit
    end

  end

  private

  def secure_params
    params.require(:doc).permit(:title, :content)
  end

  def set_doc
    @doc = Doc.find(params[:id])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/docs/_form.html.erb
<%= form_for(doc) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :content %>
  <%= f.text_area :content %>
  <%= f.submit "Submit" %>
<% end %>

app/views/docs/delete.html.erb
<h1>Docs#delete</h1>
<p>Find me in app/views/docs/delete.html.erb</p>

app/views/docs/edit.html.erb
<h1>Docs#edit</h1>
<p>Find me in app/views/docs/edit.html.erb</p>

<%= render 'form', doc: @doc %>

app/views/docs/index.html.erb
<h1>Docs#index</h1>
<p>Find me in app/views/docs/index.html.erb</p>

<% @docs.each do |d| %>
  <div class="card">
    <div class="card-header">
      <%= link_to d.title, doc_path(d) %>
    </div>
    <div class="card-block">
      <p class="card-text"><%= d.content %></p>
    </div>
  </div>
  <hr>
<% end %> 

<%= link_to "Add Document", new_doc_path %>

app/views/docs/new.html.erb
<h1>Docs#new</h1>
<p>Find me in app/views/docs/new.html.erb</p>

<%= render 'form', doc: @doc %>

app/views/docs/show.html.erb
<h1>Docs#show</h1>
<p>Find me in app/views/docs/show.html.erb</p>

<div class="card">
  <div class="card-head">
    <%= @doc.title %>
  </div>
  <div class="card-block">
    <%= @doc.content %>
  </div>
</div>
<%= link_to "Edit", edit_doc_path(@doc), class: 'btn btn-warning' %>
<%= link_to "Back to Document Overview", docs_path, class: 'btn btn-primary' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Filecabinet</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/nav" %>
    <%= render "shared/flash_message" %>

    <%= yield %>
  </body>
</html>

app/views/shared/_flash_message.html.erb
    <% if notice %>
      <p class="alert alert-info"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <%= link_to "Home", root_path, class: "nav-item nav-link" %>
      <% if current_user %>
        <%= link_to("Documents", docs_path, class: "nav-item nav-link") %>
        <%= link_to("Logout", destroy_user_session_path, method: 'delete', class: "nav-item nav-link") %>
      <% else %>  
        <%= link_to("Sign up", new_user_registration_path, class: "nav-item nav-link") %>
        <%= link_to("Login", new_user_session_path, class: "nav-item nav-link") %>
      <% end %>
    </div>
  </div>
</nav>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>



<% if current_user %>
  <%= link_to("Documents", docs_path, class: 'btn btn-primary') %>
  <%= link_to("Logout", destroy_user_session_path, method: 'delete', class: 'btn btn-warning') %>
<% else %>  
  <%= link_to("Sign up", new_user_registration_path, class: 'btn btn-primary') %>
  <%= link_to("Login", new_user_session_path, class: 'btn btn-success') %>
<% end %>